[questrade]
refresh_token = ""
access_token = ""
api_server = "https://api06.iq.questrade.com/"
expires_in = 1800
token_type = "Bearer"
expires_at = 1616095326.355846

[kraken]
key_descr = "api_0"
api_key = ""
secret = ""

[ib]
host = "127.0.0.1"

ports.gw = 4002
ports.tws = 7497
ports.order = ["gw", "tws",]

accounts.margin = "X0000000"
accounts.ira = "X0000000"
accounts.paper = "XX0000000"

# the order in which accounts will be selected (if found through
# `brokerd`) when a new symbol is loaded
accounts_order = ['paper', 'margin', 'ira']
